is_record: false
servo_rate: 0.001 # !!this should be match with controller servo rate!!
num_steps_per_cycle: 30
hanging_height: 1.83
display_joint_frame: false
display_target_frame: true
joint_limit_enforced: true
#initial_configuration: [0, 0, -0.5, 1.8, 1.03, 0, 0, -0.5, 1.8, 1.03]
initial_configuration: [0, 0, 0, 0, 1.57, 0, 0, 0, 0, 1.57]

calculate_zmp: true
plot_adjusted_foot: true
plot_guided_foot: true
camera_manipulator: true
print_computation_time: false
#release_time: 4.20
release_time: 0.5

### Toggle for RL ###
#show_viewer: true
show_viewer: false
#check_collision: true
check_collision: false


control_configuration:
  kp: [100 , 100 , 100 , 100 , 10 , 100 , 100 , 100 , 100 , 10]
  kd: [20  , 20  , 20  , 20  , 1  , 20  , 20  , 20  , 20  , 1]

workspace_configuration:
  #lower_limit: [-42.75 , -51.62 , -72.34 , 0.]
  #upper_limit: [42.75  , 15.84  , 57.34  , 122.24]
  lower_limit: [-42.75 , -15.84 , -72.34 , 0.]
  upper_limit: [42.75  , 51.62  , 57.34  , 122.24]

  #lower_cart: [-0.9 , -0.6 , 0.7]
  #upper_cart: [0.9  , 1.2  , 2.5]
  #dq_input: 0.0174533
  #dx_input: 0.01

  lower_cart: [-1.0 , -0.6 , 0.6]
  upper_cart: [1.0  , 1.4  , 2.6]
  dq_input: 0.0174533
  dx_input: 0.02
