#is_record: true
is_record: false
servo_rate: 0.001 # !!this should be match with controller servo rate!!
#show_viewer: false
show_viewer: true
num_steps_per_cycle: 30
#display_joint_frame: true
display_joint_frame: false
display_target_frame: false
actuator_type: 1 # servo mode 
q_init: [ -90,  0,	-90,	0,	0]
#q_init: [ -90,  0,	0,	0,	0]
#q_init: [ 0,  0,	0,	0,	0]

## Camera1
from: [5.4, -9.6, 4.2]
to: [1.5, 1.0, 0.5]

#from: [9.0, 0.1, 4.0]
#to: [3.5, 0.1, 1.0]

## Manipulator
#p1: [-0.3, -0.4, -0.15]
#p2: [-0.3, -0.6, -0.15]
#
#p1: [-0.3, -0.4, -0.20]
#p2: [0.3, 0.4, 0.20]

#p1: [-0.3, -0.4, -0.20]
#p2: [-0.1, 0.1, -0.1]

#p1: [-0.3, -0.4, -0.01]
#p2: [0.4, -0.90, 0.06]
